#ifndef BULGE_ERROR_HEADER
#define BULGE_ERROR_HEADER

#include <stdint.h>

typedef enum enumBulgeError {
  BULGE_ERROR_NONE = 0,
  BULGE_ERROR_DEVICE_READ,
  BULGE_ERROR_DEVICE_WRITE,
  BULGE_ERROR_FULL_FILESYSTEM,
  BULGE_ERROR_FULL_DIRECTORY,
  BULGE_ERROR_PATH_INVALID,
  BULGE_ERROR_PATH_NOT_FOUND,
  BULGE_ERROR_PATH_NOT_A_DIRECTORY,
  BULGE_ERROR_PATH_NOT_A_FILE,
  BULGE_ERROR_PATH_EXISTS,
  BULGE_ERROR_CORRUPTED_FILESYSTEM,
  BULGE_ERROR_CORRUPTED_TABLE,
  BULGE_ERROR_CORRUPTED_CHAIN,
  BULGE_ERROR_CORRUPTED_ENTRY,
  BULGE_ERROR_CORRUPTED_DIRECTORY,
  BULGE_ERROR_END_OF_DIRECTORY,
  BULGE_ERROR_ENTRY_TYPE_MISMATCH,
  BULGE_ERROR_ATTRIBUTES_NOT_CREATED,
  BULGE_ERROR_TOO_SMALL,
  BULGE_ERROR_BUG,
  BULGE_ERROR_NOT_BULGE_FS,
  BULGE_ERROR_FS_VERSION_TOO_NEW,
  BULGE_ERROR_NOT_IMPLEMENTED
} BulgeError;

const char* bulgeError_string(BulgeError error);

#endif // ifndef BULGE_ERROR_HEADER
